# config.py

# ===== UI / debug toggles
SHOW_WINDOWS = True
DRAW_OVERLAY = True
SIMPLE_LOG = False

# ===== Paths
MODEL_PATH = "mobilenet_v2_ver2.pth"
YOLO_PATH  = "yolov8n_ver1.pt"

# ===== UNet input
IMG_H, IMG_W = 160, 320
AI_THRESH_LOGIT = 0.0

# ===== Speed bounds
V_MIN, V_MAX = 11, 44
STRAIGHT_SPEED_CAP = 44
PRETURN_SPEED_CAP = 40.2
CURVE_SPEED_FLOOR = 38.5

# ===== Row sampling for centerline fit
ROW_STEP, N_ROWS, MIN_POINTS_FIT = 18, 7, 5
CHECKPOINT     = 150
CHECKPOINT_FAR = 149

# ===== Smoothing / rate limits
V_SMOOTH_A_CURVE, V_SMOOTH_A_STRAIGHT = 0.27, 0.10
V_RATE_LIMIT_CURVE, V_RATE_LIMIT_STRAIGHT = 4.5, 12.0

# ===== Straight-mode heuristics
STRAIGHT_R_ENTER_INV = 1.0/180.0
STRAIGHT_R_EXIT_INV  = 1.0/120.0
STRAIGHT_MIN_FRAMES_INV = 2
EMA_ALPHA_RINV = 0.35
EMA_ALPHA_ANG  = 0.35
ENTER_ANG = 7.0
EXIT_ANG  = 4.0
CONFIRM_N = 2

# ===== Angles & clamps
WAIT_PREBIAS_ANGLE = 3.0
OPPOSITE_LIMIT     = 4.0
TURN_ANGLE = 46.0

# ===== Turn delays (meters)
TURN_DELAY_METERS_TURN_LEFT  = 6.52
TURN_DELAY_METERS_TURN_RIGHT = 6.50
TURN_DELAY_METERS_NO_LEFT    = 6.33
TURN_DELAY_METERS_NO_RIGHT   = 6.37
TURN_DURATION_METERS = 13.5

# ===== YOLO runtime
YOLO_CONF, YOLO_IOU = 0.55, 0.45
YOLO_IMGSZ = 544
YOLO_FRAME_STRIDE_DEFAULT = 1

# ===== G-straight guards
GSTRAIGHT_VISIBLE_MAX_ANGLE = 7.0
GSTRAIGHT_PRE_MAX_ANGLE     = 5.5
GSTRAIGHT_SEEN_YOLO_MIN     = 10
GSTRAIGHT_AREA_ON           = 2000
GSTRAIGHT_SEEN_MIN          = 10
GSTRAIGHT_MAX_ANGLE         = 5.0
GSTRAIGHT_METERS_X          = 33.0
GSTRAIGHT_METERS_T          = 33.0
GSTRAIGHT_TOP_BAND          = 0.22
GSTRAIGHT_TOP_FILL          = 0.05
GSTRAIGHT_MISS_TIMEOUT      = 0.60
GSTRAIGHT_PRINT_INTERVAL    = 6

# ===== Sign areas
SIGN_AREA_THRESHOLD = 900
SIGN_PREP_AREA      = 1600
PRETURN_PREBIAS_ANGLE = 2.3
PRETURN_MAX_ANGLE     = 5.0

# ===== PID gains (default)
PID_KP = 0.2287
PID_KI = 0.0
PID_KD = 0.2853
